spring:
  application:
    name: vibe-llm
  ai:
    openai:
      base-url: http://172.16.50.149:1234/v1
      api-key: lm-studio
      chat:
        model: qwen3.5-4b-super-coder
server:
  port : 8081
